<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RealMoviesSeeder extends Seeder
{
    public function run()
    {
        DB::table('add_movies')->insert([

            [
                'title' => 'KGF Chapter 2',
                'youtube_video_id' => '0b1L9eZyGXY',
                'youtube_url' => 'https://www.youtube.com/watch?v=0b1L9eZyGXY',
                'thumbnail' => 'https://img.youtube.com/vi/0b1L9eZyGXY/maxresdefault.jpg',
                'category' => json_encode(['Action','Drama']),
                'artist_name' => 'Yash',
                'release_year' => 2022,
                'description' => 'Official trailer for KGF Chapter 2.',
                'searching_word' => 'kgf yash action drama',
                'language' => 'Kannada',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Pushpa: The Rise',
                'youtube_video_id' => 'Q1NKMPhP8PY',
                'youtube_url' => 'https://www.youtube.com/watch?v=Q1NKMPhP8PY',
                'thumbnail' => 'https://img.youtube.com/vi/Q1NKMPhP8PY/maxresdefault.jpg',
                'category' => json_encode(['Action','Thriller']),
                'artist_name' => 'Allu Arjun',
                'release_year' => 2021,
                'description' => 'Action thriller movie about smuggling.',
                'searching_word' => 'pushpa allu arjun action thriller',
                'language' => 'Telugu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Avengers: Endgame',
                'youtube_video_id' => 'TcMBFSGVi1c',
                'youtube_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'thumbnail' => 'https://img.youtube.com/vi/TcMBFSGVi1c/maxresdefault.jpg',
                'category' => json_encode(['Action','Sci-Fi']),
                'artist_name' => 'Robert Downey Jr., Chris Evans',
                'release_year' => 2019,
                'description' => 'Official trailer for Avengers: Endgame.',
                'searching_word' => 'avengers endgame marvel official trailer',
                'language' => 'English',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Spider-Man: Far From Home',
                'youtube_video_id' => 'KLjPuCUKex4',
                'youtube_url' => 'https://www.youtube.com/watch?v=KLjPuCUKex4',
                'thumbnail' => 'https://img.youtube.com/vi/KLjPuCUKex4/maxresdefault.jpg',
                'category' => json_encode(['Action','Adventure']),
                'artist_name' => 'Tom Holland',
                'release_year' => 2019,
                'description' => 'Official Spider-Man: Far From Home trailer.',
                'searching_word' => 'spiderman far from home official trailer',
                'language' => 'English',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Tiger Zinda Hai',
                'youtube_video_id' => '4hBDEM3FAvk',
                'youtube_url' => 'https://www.youtube.com/watch?v=4hBDEM3FAvk',
                'thumbnail' => 'https://img.youtube.com/vi/4hBDEM3FAvk/maxresdefault.jpg',
                'category' => json_encode(['Action','Thriller']),
                'artist_name' => 'Salman Khan, Katrina Kaif',
                'release_year' => 2017,
                'description' => 'Official trailer of Tiger Zinda Hai.',
                'searching_word' => 'tiger zinda hai official trailer salman khan',
                'language' => 'Hindi',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Zero',
                'youtube_video_id' => 'Z_T1NE1sUYo',
                'youtube_url' => 'https://www.youtube.com/watch?v=Z_T1NE1sUYo',
                'thumbnail' => 'https://img.youtube.com/vi/Z_T1NE1sUYo/maxresdefault.jpg',
                'category' => json_encode(['Drama','Romance']),
                'artist_name' => 'Shah Rukh Khan',
                'release_year' => 2018,
                'description' => 'Official trailer for Zero starring Shah Rukh Khan.',
                'searching_word' => 'zero official trailer shah rukh khan',
                'language' => 'Hindi',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Baahubali 2: The Conclusion',
                'youtube_video_id' => '9sXH51I1Wks',
                'youtube_url' => 'https://www.youtube.com/watch?v=9sXH51I1Wks',
                'thumbnail' => 'https://img.youtube.com/vi/9sXH51I1Wks/maxresdefault.jpg',
                'category' => json_encode(['Action','Epic']),
                'artist_name' => 'Prabhas',
                'release_year' => 2017,
                'description' => 'Official trailer for Baahubali 2.',
                'searching_word' => 'baahubali 2 official trailer',
                'language' => 'Hindi',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'War',
                'youtube_video_id' => 'pbIecm3NyEA',
                'youtube_url' => 'https://www.youtube.com/watch?v=pbIecm3NyEA',
                'thumbnail' => 'https://img.youtube.com/vi/pbIecm3NyEA/maxresdefault.jpg',
                'category' => json_encode(['Action']),
                'artist_name' => 'Hrithik Roshan, Tiger Shroff',
                'release_year' => 2019,
                'description' => 'Official trailer for War.',
                'searching_word' => 'war official trailer hrithik roshan',
                'language' => 'Hindi',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Sanju',
                'youtube_video_id' => 'sl2V7s8NiMA',
                'youtube_url' => 'https://www.youtube.com/watch?v=sl2V7s8NiMA',
                'thumbnail' => 'https://img.youtube.com/vi/sl2V7s8NiMA/maxresdefault.jpg',
                'category' => json_encode(['Biography','Drama']),
                'artist_name' => 'Ranbir Kapoor',
                'release_year' => 2018,
                'description' => 'Official trailer for Sanju.',
                'searching_word' => 'sanju official trailer ranbir kapoor',
                'language' => 'Hindi',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
        'title' => 'Avengers: Infinity War',
        'youtube_video_id' => '6ZfuNTqbHE8',
        'youtube_url' => 'https://www.youtube.com/watch?v=6ZfuNTqbHE8',
        'thumbnail' => 'https://img.youtube.com/vi/6ZfuNTqbHE8/maxresdefault.jpg',
        'category' => json_encode(['Action','Sci-Fi']),
        'artist_name' => 'Robert Downey Jr., Chris Evans',
        'release_year' => 2018,
        'description' => 'Official trailer for Avengers: Infinity War.',
        'searching_word' => 'avengers infinity war official trailer',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'Black Panther',
        'youtube_video_id' => 'xjDjIWPwcPU',
        'youtube_url' => 'https://www.youtube.com/watch?v=xjDjIWPwcPU',
        'thumbnail' => 'https://img.youtube.com/vi/xjDjIWPwcPU/maxresdefault.jpg',
        'category' => json_encode(['Action','Adventure']),
        'artist_name' => 'Chadwick Boseman',
        'release_year' => 2018,
        'description' => 'Official trailer for Black Panther.',
        'searching_word' => 'black panther official trailer marvel',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'Black Panther: Wakanda Forever',
        'youtube_video_id' => '_Z3QKkl1WyM',
        'youtube_url' => 'https://www.youtube.com/watch?v=_Z3QKkl1WyM',
        'thumbnail' => 'https://img.youtube.com/vi/_Z3QKkl1WyM/maxresdefault.jpg',
        'category' => json_encode(['Action','Drama']),
        'artist_name' => 'Letitia Wright',
        'release_year' => 2022,
        'description' => 'Official trailer for Black Panther: Wakanda Forever.',
        'searching_word' => 'black panther wakanda forever official trailer',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'Spider‑Man: No Way Home',
        'youtube_video_id' => 'JfVOs4VSpmA',
        'youtube_url' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
        'thumbnail' => 'https://img.youtube.com/vi/JfVOs4VSpmA/maxresdefault.jpg',
        'category' => json_encode(['Action','Adventure']),
        'artist_name' => 'Tom Holland',
        'release_year' => 2021,
        'description' => 'Official teaser trailer for Spider‑Man: No Way Home.',
        'searching_word' => 'spiderman no way home official trailer',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'The Little Mermaid (2023)',
        'youtube_video_id' => 'y1HXcR-8sFI',
        'youtube_url' => 'https://www.youtube.com/watch?v=y1HXcR-8sFI',
        'thumbnail' => 'https://img.youtube.com/vi/y1HXcR-8sFI/maxresdefault.jpg',
        'category' => json_encode(['Family','Adventure']),
        'artist_name' => 'Halle Bailey',
        'release_year' => 2023,
        'description' => 'Official trailer for The Little Mermaid (2023).',
        'searching_word' => 'the little mermaid official trailer 2023',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'Detective Pikachu',
        'youtube_video_id' => 'xNcJZq24AMg',
        'youtube_url' => 'https://www.youtube.com/watch?v=xNcJZq24AMg',
        'thumbnail' => 'https://img.youtube.com/vi/xNcJZq24AMg/maxresdefault.jpg',
        'category' => json_encode(['Adventure','Family']),
        'artist_name' => 'Ryan Reynolds',
        'release_year' => 2019,
        'description' => 'Official trailer for Detective Pikachu.',
        'searching_word' => 'detective pikachu official trailer',
        'language' => 'English',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],

        ]);
    }
}
